Models/Group.cs
using System.ComponentModel.DataAnnotations;

public class Group {
    [Key]
    public int Id {get; set;}
    [Required(ErrorMessage = "Geen naam gevonden")]
    public string Titel { get; set; }
    [Required(ErrorMessage = "Er is geen topic gevonden.")]
    public string Topic {get; set;}
    [Required(ErrorMessage = "Er is geen leeftijdscategorie gevonden")]
    public int Leeftijdscategorie {get; set;}

}

Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace webapplication.Controllers
{
    public class GroupController : Controller
    {
        private readonly ChatDbContext _context;

        public GroupController(ChatDbContext context)
        {
            _context = context;
        }

        // GET: PriveChat
        public async Task<IActionResult> Index(string zoek, string topic, string age)
        {
            if (User.IsInRole("Moderator")) { ViewData["Moderator"] = true; }
            ViewData["topics"] = await _context.Groups.ToListAsync();
            if (zoek != null)
            {
                ViewData["Zoek"] = zoek;
                return View(await Zoek(_context.Groups, zoek).ToListAsync());
            }
            if (topic != null)
            {
                return View(await Topic(_context.Groups, topic).ToListAsync());
            }
            if (age != null)
            {
                return View(await Age(_context.Groups, age).ToListAsync());

            }
            return View(await _context.Groups.ToListAsync());
        }

        public IQueryable<Group> Zoek(IQueryable<Group> lijst, string zoek)
        {
            return lijst.Where(p => p.Titel.ToLower().Contains(zoek.ToLower()));
        }

        public IQueryable<Group> Topic(IQueryable<Group> lijst, string topic)
        {
            return lijst.Where(p => p.Topic.ToLower().Contains(topic.ToLower()));
        }

        public IQueryable<Group> Age(IQueryable<Group> lijst, string age)
        {
            switch (age)
            {
                case "low":
                    return lijst.Where(p => p.Leeftijdscategorie < 16);

                case "middle":
                    return lijst.Where(p => p.Leeftijdscategorie > 15 && p.Leeftijdscategorie < 19);

                default:
                    return lijst.Where(p => p.Leeftijdscategorie > 18);
            }

        }


        // GET: PriveChat/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var groups = await _context.Groups
                .FirstOrDefaultAsync(m => m.Id == id);
            if (groups == null)
            {
                return NotFound();
            }

            return View(groups);
        }

        // GET: PriveChat/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PriveChat/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titel,Topic,Leeftijdscategory")] Group groups)
        {
            if (ModelState.IsValid)
            {
                _context.Add(groups);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(groups);
        }

        // GET: GroupChat/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var groups = await _context.Groups.FindAsync(id);
            if (groups == null)
            {
                return NotFound();
            }
            return View(groups);
        }

        // POST: GroupChat/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titel,Topic,Leeftijdscategory")] Group groups)
        {
            if (id != groups.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(groups);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GroupChatsExists(groups.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(groups);
        }

        // GET: PriveChat/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var groups = await _context.Groups
                .FirstOrDefaultAsync(m => m.Id == id);
            if (groups == null)
            {
                return NotFound();
            }

            return View(groups);
        }

        // POST: PriveChat/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var groups = await _context.Groups.FindAsync(id);
            _context.Groups.Remove(groups);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GroupChatsExists(int id)
        {
            return _context.Groups.Any(e => e.Id == id);
        }
    }
}

Controllers/PriveChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using webapplication.Areas.Identity.Data;
using webapplication.Models;

namespace webapplication.Controllers
{
    public class PriveChatController : Controller
    {
        private readonly ChatDbContext _ChatContext;
        private readonly UserManager<Gebruiker> _userManager;
        private readonly GebruikerDbContext _GebruikerContext;


        public PriveChatController(ChatDbContext ChatContext, UserManager<Gebruiker> userManager, GebruikerDbContext GebruikerContext)
        {
            _ChatContext = ChatContext;
            _userManager = userManager;
            _GebruikerContext = GebruikerContext;
        }

        // GET: PriveChat
        public async Task<IActionResult> Index()
        {
            if (User.IsInRole("Hulpverlener"))
            {
                var HulpverlenerId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                var namen = new List<string>();
                foreach (var item in await _ChatContext.PriveChat.Where(p => p.Afzender == HulpverlenerId || p.Ontvanger == HulpverlenerId).ToListAsync())
                {
                    if (item.Afzender == HulpverlenerId)
                    {
                        if (_GebruikerContext.Clients.Where(u => u.Id == item.Ontvanger).Any() == true)
                        {
                            var naam = _GebruikerContext.Clients.Where(u => u.Id == item.Ontvanger).FirstOrDefault().Email;
                            namen.Add(naam);
                        }
                    }
                    else
                    {
                        var naam = _GebruikerContext.Clients.Where(u => u.Id == item.Afzender).FirstOrDefault().Email;
                        namen.Add(naam);
                    }
                }
                namen.Sort();
                Int32 index = namen.Count - 1;
                while (index > 0)
                {
                    if (namen[index] == namen[index - 1])
                    {
                        if (index < namen.Count - 1)
                            (namen[index], namen[namen.Count - 1]) = (namen[namen.Count - 1], namen[index]);
                        namen.RemoveAt(namen.Count - 1);
                        index--;
                    }
                    else
                        index--;
                }
                ViewData["HulpverlenerNamen"] = "true";
                ViewBag.HulpverlenerNamen = namen;
                return View(_ChatContext.PriveChat.Where(p => p.Afzender == HulpverlenerId || p.Ontvanger == HulpverlenerId).ToList());
            } else {
            if (User.IsInRole("Client"))
            {
                ViewData["Client"] = true;
                var ClientId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                var idHulp = _GebruikerContext.Clients.Where(u => u.Id == ClientId).FirstOrDefault().hulpverlenerId;
                ViewData["ClientHulpverlener"] = idHulp;
            }
            }
            return View(await _ChatContext.PriveChat.ToListAsync());
        }

        // GET: PriveChat/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PriveChat/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DateTime,Ontvanger,Afzender,Body")] PriveChat priveChat)
        {
            if (ModelState.IsValid)
            {
                _ChatContext.Add(priveChat);
                await _ChatContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(priveChat);
        }

        // GET: PriveChat/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var priveChat = await _ChatContext.PriveChat.FindAsync(id);
            if (priveChat == null)
            {
                return NotFound();
            }
            return View(priveChat);
        }

        // POST: PriveChat/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DateTime,Ontvanger,Afzender")] PriveChat priveChat)
        {
            if (id != priveChat.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _ChatContext.Update(priveChat);
                    await _ChatContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PriveChatExists(priveChat.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(priveChat);
        }

        // GET: PriveChat/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var priveChat = await _ChatContext.PriveChat
                .FirstOrDefaultAsync(m => m.Id == id);
            if (priveChat == null)
            {
                return NotFound();
            }

            return View(priveChat);
        }

        // POST: PriveChat/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var priveChat = await _ChatContext.PriveChat.FindAsync(id);
            _ChatContext.PriveChat.Remove(priveChat);
            await _ChatContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PriveChatExists(int id)
        {
            return _ChatContext.PriveChat.Any(e => e.Id == id);
        }
    }
}

Views/Group/Create.cshtml
@model Group

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

<h4>Group</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titel" class="control-label"></label>
                <input asp-for="Titel" class="form-control" />
                <span asp-validation-for="Titel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Topic" class="control-label"></label>
                <input asp-for="Topic" class="form-control" />
                <span asp-validation-for="Topic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Leeftijdscategorie" class="control-label"></label>
                <input asp-for="Leeftijdscategorie" class="form-control" />
                <span asp-validation-for="Leeftijdscategorie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

</body>
</html>

Views/Group/Index.cshtml
@using Microsoft.AspNetCore.Identity
@model IEnumerable<Group>
@inject UserManager<Gebruiker> UserManager

@{
	var topics = ViewData["topics"] as List<Group>;
	Layout = "";
}

<!DOCTYPE html>
<html>

<head>
	<title></title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<style>
		.chatbox {
			overflow: scroll;
		}
	</style>
</head>

<body class="container-sm">
	<partial name="_NavPartial"></partial>
	<div class="container-sm" style="position: relative; top: 5rem;">

		<article class="d-flex justify-content-between">
			<a class="btn btn-outline-secondary flex-fill d-flex justify-content-center" asp-area=""
				asp-controller="PriveChat" asp-action="Index">Prive chat</a>&nbsp;
			<section class="btn btn-secondary flex-fill d-flex justify-content-center">zelfhulp groepen</section>
		</article>
		<h3 class="flex-fill d-flex justify-content-center">Zelfhulpgroepen</h3>
		<article class="d-flex justify-content-between" style="height: 60vh; overflow: scroll;">
			<div class="w-50 border border-secondary  p-2">
				<h4 class="flex-fill d-flex justify-content-center">Groepen</h4>

				<form action="/Group/Index">
					<div class="d-flex justify-content-between">
						<input class="form-control searchBar" type="text" name="zoek" value='@ViewData["Zoek"]' placeholder="Zoek op naam">
						<input class="btn btn-primary searchBar" type="submit" value="Zoek!">
					</div>
				</form>

				<div class="d-flex justify-content-between m-2">
					<div class="dropdown">
						<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
							data-bs-toggle="dropdown" aria-expanded="false">
							Leeftijd
						</button>
						<ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
							<li><a class="dropdown-item" asp-controller="Group" asp-action="Index"
									asp-route-age="low">&#60;16</a></li>
							<li><a class="dropdown-item" asp-controller="Group" asp-action="Index"
									asp-route-age="middle">16-18</a></li>
							<li><a class="dropdown-item" asp-controller="Group" asp-action="Index"
									asp-route-age="high">18&#62;</a></li>
						</ul>
					</div>
					<div class="dropdown">
						<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton2"
							data-bs-toggle="dropdown" aria-expanded="false">
							Topic
						</button>
						<ul class="dropdown-menu" aria-labelledby="dropdownMenuButton2">
							@foreach (var item in topics)
							{
								<li><a class="dropdown-item" asp-controller="Group" asp-action="Index"
									asp-route-topic="@item.Topic">@item.Topic</a></li>
							}
						</ul>
					</div>
				</div>
				<div>
					@foreach (var item in Model)
					{
						<a onclick="getGroupChat(@item.Id)"> @item.Titel </a><br />
					}
				</div>
			</div>
			<div class="w-100 border border-secondary p-2 chatbox" style="height: 100%;">
				<div class="chat">

				</div>
				<section class="d-flex justify-content-between mt-auto">
					<input class="form-control m-1 chatInput" type="text" name="">
					<button class="btn btn-success m-1" onclick="createChat()">Verstuur</button>
				</section>
			</div>
		</article>
	</div>


	<script>
		var selected = 0;
		var oldSelected = 0;
		var list = [];
		var setup = false;
		function getGroupChat(id) {
			setup = false;
			window.history.pushState("", "", '/Group');
			selected = id;
			fetch("api/GroupChatApi/" + id, {
				method: "GET"
			}).then(r => {
				if (r.status != 200) {
					throw "Status: " + r.status;
				} else {
					return r.json();
				}
			}).then(j => {
				chat = document.querySelector(".chat");
				chat.innerHTML = "";
				for (let i = 0; i < j.length; i++) {
					var p = document.createElement("p");
					p.classList.add("w-100");
					if('@ViewData["Moderator"]' == "True"){
						if(j[i].meld != 0) {
							p.innerHTML = j[i].dateTime + ": " + j[i].body + "<span style='float:right; color: red;' onclick='DeleteChat("+j[i].id+")'>Delete</span> <span style='float:right; color: orange;'>Gemeld! |</span>";
						} else {
							p.innerHTML = j[i].dateTime + ": " + j[i].body + "<span style='float:right; color: red;' onclick='DeleteChat("+j[i].id+")'>Delete</span>";
						}
					} else {
						if(j[i].afzender != "@UserManager.GetUserId(User)"){
							if(j[i].meld != 0) {
								p.innerHTML = j[i].dateTime + ": " + j[i].body + "<span style='float:right; color: orange;'> Gemeld </span>";
							} else {
								p.innerHTML = j[i].dateTime + ": " + j[i].body + "<span style='float:right; color: red;' onclick='meld("+ j[i].id +")'> Meld </span>";
							}
						} else {
							p.innerHTML = j[i].dateTime + ": " + j[i].body;
						}
					}
					chat.appendChild(p);
				}
			}).catch(r => alert("Er is een fout op getreden " + r));
		}

		function createChat() {
			var currentdate = new Date();
			var datetime = "Last Sync: " + currentdate.getDay() + "/" + currentdate.getMonth()
				+ "/" + currentdate.getFullYear() + " "
				+ currentdate.getHours() + ":"
				+ currentdate.getMinutes() + ":" + currentdate.getSeconds();
			var input = document.querySelector(".chatInput").value;
			fetch("api/GroupChatApi/", {
				method: "POST",
				body: JSON.stringify({ "DateTime": datetime, "Ontvanger": "1", "Afzender": "@UserManager.GetUserId(User)", "Body": input, "GroupId": selected }),
				headers: { "content-type": "application/json" }
			}).then(r => {
				if (r.status != 201) {
					throw "Status: " + r.status;
				} else {
					return r.json();
				}
			}).then(j => {
				chat = document.querySelector(".chat");
				var p = document.createElement("p");
				if('@ViewData["Moderator"]' == "True"){
					if(j.meld != 0) {
						p.innerHTML = j.dateTime + ": " + j.body + "<span style='float:right; color: orange;'>Gemeld!</span> | <span style='float:right; color: red;' onclick='DeleteChat("+j.id+")'>Delete</span>";
					} else {
						p.innerHTML = j.dateTime + ": " + j.body + "<span style='float:right; color: red;' onclick='DeleteChat("+j.id+")'>Delete</span>";
					}
				} else {
						p.innerHTML = j.dateTime + ": " + j.body;
				}
				chat.appendChild(p);
				list.push(j);
				document.querySelector(".chatInput").value = "";
			}).catch(r => alert("Er is een fout op getreden " + r));
		}

		setInterval(function () {
			if (selected != 0) {
				if (oldSelected != selected && list != []) {
					list = [];
				}
				oldSelected = selected;
				fetch("api/GroupChatApi/" + selected, {
					method: "GET"
				}).then(r => {
					if (r.status != 200) {
						throw "Status: " + r.status;
					} else {
						return r.json();
					}
				}).then(j => {
					if (setup != true) {
						list = j;
						setup = true;
					} else {
						if (JSON.stringify(list) != JSON.stringify(j)) {
							list = j;
							chat = document.querySelector(".chat");
							chat.innerHTML = "";
							for (let i = 0; i < j.length; i++) {
								var p = document.createElement("p");
								p.classList.add("w-100");
								if('@ViewData["Moderator"]' == "True"){
									if(j[i].meld != 0) {
										p.innerHTML = j[i].dateTime + ": " + j[i].body + "<span style='float:right; color: red;' onclick='DeleteChat("+j[i].id+")'>Delete</span> <span style='float:right; color: orange;'>Gemeld! |</span>";
									} else {
										p.innerHTML = j[i].dateTime + ": " + j[i].body + "<span style='float:right; color: red;' onclick='DeleteChat("+j[i].id+")'>Delete</span>";
									}
								} else {
									if(j[i].afzender != "@UserManager.GetUserId(User)"){
										if(j[i].meld != 0) {
											p.innerHTML = j[i].dateTime + ": " + j[i].body + "<span style='float:right; color: orange;'> Gemeld </span>";
										} else {
											p.innerHTML = j[i].dateTime + ": " + j[i].body + "<span style='float:right; color: red;' onclick='meld("+ j[i].id +")'> Meld </span>";
										}
									} else {
										p.innerHTML = j[i].dateTime + ": " + j[i].body;
									}
							}
							chat.appendChild(p);
						}
					}

					}
				}).catch(r => alert("Er is een fout op getreden " + r));
			}
		}, 5000);

		function meld(id)
		{
			fetch("api/GroupChatApi/" + id, {
				method: "PUT",
			}).then(r => {
				if (r.status != 200) {
					throw "Status: " + r.status;
				} else {
					return r.json();
				}
			}).then(j => {
				setup = false;
				chat = document.querySelector(".chat");
				chat.innerHTML = "";
				for (let i = 0; i < j.length; i++) {
					var p = document.createElement("p");
					p.classList.add("w-100");
					if('@ViewData["Moderator"]' == "True"){
						if(j[i].meld != 0) {
							p.innerHTML = j[i].dateTime + ": " + j[i].body + "<span style='float:right; color: red;' onclick='DeleteChat("+j[i].id+")'>Delete</span> <span style='float:right; color: orange;'>Gemeld! |</span>";
						} else {
							p.innerHTML = j[i].dateTime + ": " + j[i].body + "<span style='float:right; color: red;' onclick='DeleteChat("+j[i].id+")'>Delete</span>";
						}
					} else {
						if(j[i].afzender != "@UserManager.GetUserId(User)"){
							if(j[i].meld != 0) {
								p.innerHTML = j[i].dateTime + ": " + j[i].body + "<span style='float:right; color: orange;'> Gemeld </span>";
							} else {
								p.innerHTML = j[i].dateTime + ": " + j[i].body + "<span style='float:right; color: red;' onclick='meld("+ j[i].id +")'> Meld </span>";
							}
						} else {
							p.innerHTML = j[i].dateTime + ": " + j[i].body;
						}
					}
					chat.appendChild(p);
				}
			}).catch(r => alert("Er is een fout op getreden " + r));
		}

		function DeleteChat(id){
			setup = false;
			fetch("api/GroupChatApi/" + id, {
					method: "DELETE"
				}).then(r => {
					if (r.status != 200) {
						throw "Status: " + r.status;
					} else {
						return r.json();
					}
				}).then(j => {
				chat = document.querySelector(".chat");
				chat.innerHTML = "";
				for (let i = 0; i < j.length; i++) {
					var p = document.createElement("p");
					p.classList.add("w-100");
					if('@ViewData["Moderator"]' == "True"){
						if(j[i].meld != 0) {
							p.innerHTML = j[i].dateTime + ": " + j[i].body + "<span style='float:right; color: red;' onclick='DeleteChat("+j[i].id+")'>Delete</span> <span style='float:right; color: orange;'>Gemeld! |</span>";
						} else {
							p.innerHTML = j[i].dateTime + ": " + j[i].body + "<span style='float:right; color: red;' onclick='DeleteChat("+j[i].id+")'>Delete</span>";
						}
					} else {
						if(j[i].afzender != "@UserManager.GetUserId(User)"){
							if(j[i].meld != 0) {
								p.innerHTML = j[i].dateTime + ": " + j[i].body + "<span style='float:right; color: orange;'> Gemeld </span>";
							} else {
								p.innerHTML = j[i].dateTime + ": " + j[i].body + "<span style='float:right; color: red;' onclick='meld("+ j[i].id +")'> Meld </span>";
							}
						} else {
							p.innerHTML = j[i].dateTime + ": " + j[i].body;
						}
					}
					chat.appendChild(p);
				}
				}).catch(r => alert("Er is een fout op getreden " + r));
		}
	</script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>